### ISSUE TITLE
Recent unlocks icon

### ISSUE THREAD

**Issue by reivdialect** [rfindley/wk_selfstudy#2]
On both Chrome (Version 51.0.2704.63) and Firefox (46.0.1) there's a problem with the recent unlocks icon when doing a quiz.

![awkward_radicals](https://cloud.githubusercontent.com/assets/19204412/15695525/7311931a-27eb-11e6-9e87-f46420988de6.png)

The following css code seems to serve as an easy fix and makes sure the icons stay behind the quiz box.

`
.recently-unlocked-badge:before {
   z-index: 0 !important
}
`

**Comment by rfindley** [comment]
Rather than lower the z-index of the native WK stuff, let's raise the z-index of the userscript.  Can you look up the z-index value they're using?

**Comment by reivdialect** [comment]
Their current code for the icon:
`
.recently-unlocked-badge:before { z-index: 999; }
`

**Comment by rfindley** [comment]
K.  I'll make a quick change to add z-index to self-study's top-level element (and any sub-elements, if there are any).

Thanks!
